// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: shipping/shipping.proto

package shipping

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShippingItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductCode   string                 `protobuf:"bytes,1,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShippingItem) Reset() {
	*x = ShippingItem{}
	mi := &file_shipping_shipping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingItem) ProtoMessage() {}

func (x *ShippingItem) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_shipping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingItem.ProtoReflect.Descriptor instead.
func (*ShippingItem) Descriptor() ([]byte, []int) {
	return file_shipping_shipping_proto_rawDescGZIP(), []int{0}
}

func (x *ShippingItem) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *ShippingItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CalculateShippingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         []*ShippingItem        `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateShippingRequest) Reset() {
	*x = CalculateShippingRequest{}
	mi := &file_shipping_shipping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateShippingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateShippingRequest) ProtoMessage() {}

func (x *CalculateShippingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_shipping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateShippingRequest.ProtoReflect.Descriptor instead.
func (*CalculateShippingRequest) Descriptor() ([]byte, []int) {
	return file_shipping_shipping_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateShippingRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CalculateShippingRequest) GetItems() []*ShippingItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CalculateShippingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryDays  int32                  `protobuf:"varint,1,opt,name=delivery_days,json=deliveryDays,proto3" json:"delivery_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateShippingResponse) Reset() {
	*x = CalculateShippingResponse{}
	mi := &file_shipping_shipping_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateShippingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateShippingResponse) ProtoMessage() {}

func (x *CalculateShippingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_shipping_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateShippingResponse.ProtoReflect.Descriptor instead.
func (*CalculateShippingResponse) Descriptor() ([]byte, []int) {
	return file_shipping_shipping_proto_rawDescGZIP(), []int{2}
}

func (x *CalculateShippingResponse) GetDeliveryDays() int32 {
	if x != nil {
		return x.DeliveryDays
	}
	return 0
}

var File_shipping_shipping_proto protoreflect.FileDescriptor

const file_shipping_shipping_proto_rawDesc = "" +
	"\n" +
	"\x17shipping/shipping.proto\"M\n" +
	"\fShippingItem\x12!\n" +
	"\fproduct_code\x18\x01 \x01(\tR\vproductCode\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"Z\n" +
	"\x18CalculateShippingRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12#\n" +
	"\x05items\x18\x02 \x03(\v2\r.ShippingItemR\x05items\"@\n" +
	"\x19CalculateShippingResponse\x12#\n" +
	"\rdelivery_days\x18\x01 \x01(\x05R\fdeliveryDays2P\n" +
	"\bShipping\x12D\n" +
	"\tCalculate\x12\x19.CalculateShippingRequest\x1a\x1a.CalculateShippingResponse\"\x00B9Z7github/araujo-angel/microservices-proto/golang/shippingb\x06proto3"

var (
	file_shipping_shipping_proto_rawDescOnce sync.Once
	file_shipping_shipping_proto_rawDescData []byte
)

func file_shipping_shipping_proto_rawDescGZIP() []byte {
	file_shipping_shipping_proto_rawDescOnce.Do(func() {
		file_shipping_shipping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shipping_shipping_proto_rawDesc), len(file_shipping_shipping_proto_rawDesc)))
	})
	return file_shipping_shipping_proto_rawDescData
}

var file_shipping_shipping_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_shipping_shipping_proto_goTypes = []any{
	(*ShippingItem)(nil),              // 0: ShippingItem
	(*CalculateShippingRequest)(nil),  // 1: CalculateShippingRequest
	(*CalculateShippingResponse)(nil), // 2: CalculateShippingResponse
}
var file_shipping_shipping_proto_depIdxs = []int32{
	0, // 0: CalculateShippingRequest.items:type_name -> ShippingItem
	1, // 1: Shipping.Calculate:input_type -> CalculateShippingRequest
	2, // 2: Shipping.Calculate:output_type -> CalculateShippingResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shipping_shipping_proto_init() }
func file_shipping_shipping_proto_init() {
	if File_shipping_shipping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shipping_shipping_proto_rawDesc), len(file_shipping_shipping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shipping_shipping_proto_goTypes,
		DependencyIndexes: file_shipping_shipping_proto_depIdxs,
		MessageInfos:      file_shipping_shipping_proto_msgTypes,
	}.Build()
	File_shipping_shipping_proto = out.File
	file_shipping_shipping_proto_goTypes = nil
	file_shipping_shipping_proto_depIdxs = nil
}
